"""Add cascade on delete to tables related with Project - 2

Revision ID: 1f564b908a5a
Revises: ab559c603cf2
Create Date: 2022-02-07 01:59:21.269647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f564b908a5a'
down_revision = 'ab559c603cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
