"""Created project1 model

Revision ID: 5ac4c50c9d8d
Revises: c4b798925338
Create Date: 2023-05-11 08:10:01.742659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac4c50c9d8d'
down_revision = 'c4b798925338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data_total_count', sa.Integer(), nullable=True),
    sa.Column('data_sample_count', sa.Integer(), nullable=True),
    sa.Column('dir_name', sa.String(), nullable=True),
    sa.Column('company_info', sa.String(), nullable=True),
    sa.Column('extended_properties', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project1_id'), 'project1', ['id'], unique=False)
    op.create_index(op.f('ix_project1_name'), 'project1', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project1_name'), table_name='project1')
    op.drop_index(op.f('ix_project1_id'), table_name='project1')
    op.drop_table('project1')
    # ### end Alembic commands ###
