"""Add Column state_id to Project table

Revision ID: 70393e6dbdbd
Revises: 40f23ea4e3af
Create Date: 2022-02-10 07:03:29.497250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70393e6dbdbd'
down_revision = '40f23ea4e3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'state_id')
    # ### end Alembic commands ###
