"""Add column updated_at to Project model

Revision ID: 77c8af07acce
Revises: 1e4de8589b40
Create Date: 2022-01-06 05:31:14.056256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c8af07acce'
down_revision = '1e4de8589b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'updated_at')
    # ### end Alembic commands ###
