"""Add column company to Customer model

Revision ID: 8332dc02e477
Revises: 0cabbc1aece0
Create Date: 2021-11-23 07:55:04.686529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8332dc02e477'
down_revision = '0cabbc1aece0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'company')
    # ### end Alembic commands ###
