"""Add cascade on delete to tables related with Project

Revision ID: ab559c603cf2
Revises: 8838f78e0f74
Create Date: 2022-02-07 01:53:50.125394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab559c603cf2'
down_revision = '8838f78e0f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projectannotationclass_project_id_fkey', 'projectannotationclass', type_='foreignkey')
    op.create_foreign_key(None, 'projectannotationclass', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('projectannotationerror_project_id_fkey', 'projectannotationerror', type_='foreignkey')
    op.create_foreign_key(None, 'projectannotationerror', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projectannotationerror', type_='foreignkey')
    op.create_foreign_key('projectannotationerror_project_id_fkey', 'projectannotationerror', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'projectannotationclass', type_='foreignkey')
    op.create_foreign_key('projectannotationclass_project_id_fkey', 'projectannotationclass', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
