"""Set default value to state_id of Project

Revision ID: b1fe564ba4a9
Revises: 70393e6dbdbd
Create Date: 2022-02-10 07:30:21.897858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fe564ba4a9'
down_revision = '70393e6dbdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
