"""add reviewer and inspector

Revision ID: c4b798925338
Revises: b1fe564ba4a9
Create Date: 2022-03-21 07:26:04.547499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b798925338'
down_revision = 'b1fe564ba4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.add_column('group', sa.Column('is_reviewer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_reviewer')
    op.drop_column('group', 'is_user')
    # ### end Alembic commands ###
