"""Add cascade on delete to tables related with Project - 3

Revision ID: 0060edebdfcb
Revises: 1f564b908a5a
Create Date: 2022-02-07 02:10:59.601318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0060edebdfcb'
down_revision = '1f564b908a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
