"""Add column reviewer_id to User model

Revision ID: 2253e3b6a225
Revises: 77c8af07acce
Create Date: 2022-01-17 23:48:48.650876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2253e3b6a225'
down_revision = '77c8af07acce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'reviewer_id')
    # ### end Alembic commands ###
