"""Add cascade on delete to tables related with Project - 4

Revision ID: 5c2c8f791879
Revises: 0060edebdfcb
Create Date: 2022-02-07 02:18:43.439936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2c8f791879'
down_revision = '0060edebdfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_project_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_project_id_fkey', 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
