"""Use backref in Task model

Revision ID: 8838f78e0f74
Revises: 2253e3b6a225
Create Date: 2022-01-18 00:25:02.185388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8838f78e0f74'
down_revision = '2253e3b6a225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
